apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-test
    image: nginx
    # command:
      # - sleep
      # - "3600"
    # imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
#  restartPolicy: Always
