---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
#  annotations:
#    eks.amazonaws.com/role-arn: arn:aws:iam::$account:role/$role_name
  labels:
    app.kubernetes.io/name: debugger
  name: debugger

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debugger
  labels:
    app.kubernetes.io/name: debugger
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: debugger
  template:
    metadata:
      labels:
        app.kubernetes.io/name: debugger
    spec:
      serviceAccountName: debugger
      containers:
        - name: debugger
          image: raphael1021/debugger:latest
          command: ["sleep", "infinity"]
          resources: {}
